---
- hosts: default
  become: yes
  tasks:
    - name: Update and install packages
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Group management
      ansible.builtin.group:
        name: default
        state: present

    - name: User management
      ansible.builtin.user:
        name: default
        shell: /bin/bash
        create_home: true
        groups: default,sudo
        append: true
        password: "{{ lookup('ansible.builtin.env', 'TEMP_PASS') | password_hash('sha512') }}"

    - name: Install OpenSSH
      ansible.builtin.apt:
        name: openssh-server
        state: latest
        update_cache: yes

    - name: Start,Enable SSH service
      ansible.builtin.systemd:
        name: sshd
        state: started
        enabled: true
        masked: false

    - name: Sudoers
      community.general.sudoers:
        name: default
        user: default
        commands: ALL
        nopassword: true
        setenv: true
        sudoers_path: /etc/sudoers.d
        state: present
        validation: required

    - name: Create SSH dir
      ansible.builtin.file:
        path: "/home/default/.ssh"
        state: directory
        mode: '0700'
        owner: default
        group: default

    - name: Add SSH pubkey
      ansible.posix.authorized_key:
        user: default
        state: present
        key: "{{ lookup('ansible.builtin.file', lookup('ansible.builtin.env', 'HOME') + '/.ssh/k8_ed25519.pub') }}"

    - name: Ensure systemd/network dir exists
      ansible.builtin.file:
        path: /etc/systemd/network
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: systemd-networkd conf
      ansible.builtin.copy:
        dest: /etc/systemd/network/20-dhcp.network
        content: |
          [Match]
          Name=e*

          [Network]
          DHCP=yes
        owner: root
        group: root
        mode: '0644'
      notify: Restart systemd-networkd

    - name: systemd-networkd service
      ansible.builtin.systemd:
        name: systemd-networkd
        enabled: yes
        state: started

    - name: systemd-resolved service
      ansible.builtin.systemd:
        name: systemd-resolved
        enabled: yes
        state: started

    - name: Link resolved to resolv.conf
      ansible.builtin.file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link
        force: yes

    - name: KVM/QEMU Filesystem cache sync
      ansible.builtin.command: sync
      changed_when: false

  handlers:
    - name: Restart systemd-networkd
      ansible.builtin.service:
        name: systemd-networkd
        state: restarted
        enabled: yes
