apiVersion: v1
kind: ConfigMap
metadata:
  name: envconfmap
data:
  key: value
  another: one
  multiline.conf: |
    host=localhost
    enable=yes
  mult.file: |
    property.one=qwe
    property.two=asd
